load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "way",
    embed = [":way_lib"],
    importpath = "github.com/Waryway/Wayframe/tools/way",
    visibility = ["//visibility:public"],
)

go_library(
    name = "way_lib",
    srcs = ["main.go"],
    importpath = "github.com/Waryway/Wayframe/tools/way",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/cli",
        "//pkg/logger",
    ],
)
