load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "stdlib_lib",
    srcs = ["main.go"],
    importpath = "github.com/Waryway/Wayframe/examples/stdlib",
    visibility = ["//visibility:private"],
    deps = [
        "//pkg/config",
        "//pkg/logger",
        "//pkg/server",
        "//pkg/server/stdlib",
    ],
)

go_binary(
    name = "stdlib",
    embed = [":stdlib_lib"],
    visibility = ["//visibility:public"],
)
