load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fiber",
    srcs = ["server.go"],
    importpath = "github.com/Waryway/Wayframe/pkg/server/fiber",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/server",
        "@com_github_gofiber_fiber_v2//:fiber",
    ],
)
